import { Fragment } from "react";

import "../styles/globals.css";
import Head from "next/head";

import { UserProvider } from "@auth0/nextjs-auth0";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { ApolloProvider } from "@apollo/client";
import { client } from "../services/apollo-client";

const theme = createTheme({
  palette: {
    type: "light",
    primary: {
      main: "#304FF3",
    },
    secondary: {
      main: "#191919",
    },
    info: {
      main: "#0098CE",
    },
  },
  typography: {
    fontFamily: "Oswald",
  },
});

function MyApp({ Component, pageProps }) {
  // eslint-disable-next-line react/jsx-props-no-spreading
  return (
    <Fragment>
      <Head>
        <title>Unostars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApolloProvider client={client}>
        <UserProvider>
          <ThemeProvider theme={theme}>
            <Component {...pageProps} />;
          </ThemeProvider>
        </UserProvider>
      </ApolloProvider>
    </Fragment>
  );
}

export default MyApp;
