import { Fragment } from "react";

import "../styles/globals.css";
import Head from "next/head";

import { UserProvider } from "@auth0/nextjs-auth0";
import { ApolloProvider } from "@apollo/client";
import { client } from "../services/apollo-client";
import { Provider } from "react-redux";
import store from "../redux/store";

import { CustomThemeProvider } from "../components";

function MyApp({ Component, pageProps }) {
  // eslint-disable-next-line react/jsx-props-no-spreading

  return (
    <Fragment>
      <Head>
        <title>Unostars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApolloProvider client={client}>
        <Provider store={store}>
          <UserProvider>
            <CustomThemeProvider>
              <Component {...pageProps} />;
            </CustomThemeProvider>
          </UserProvider>
        </Provider>
      </ApolloProvider>
    </Fragment>
  );
}

export default MyApp;
