import { Fragment } from "react";

import Head from "next/head";

import { Navbar } from "../components";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Unostars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        index.js
      </main>
    </Fragment>
  );
}
